import {env} from "cloudflare:workers";
import {z} from "zod";
import {grossFreight,tripSchema,expenseSchema,revenueSchema,type Trip,type Expense,type Revenue,type Company} from "./finance";
export function db(){if(!env.DB)throw new Error("Banco indisponível");return env.DB;}
export function owner(request:Request){const id=request.headers.get("oai-authenticated-user-id");if(!id)throw new Response("Entre na sua conta para continuar.",{status:401});const origin=request.headers.get("origin");if(request.method!=="GET"&&origin&&origin!==new URL(request.url).origin)throw new Response("Origem inválida",{status:403});return id;}
export function failure(e:unknown){if(e instanceof Response)return e;if(e instanceof z.ZodError||e instanceof SyntaxError)return Response.json({error:"Confira os campos, datas e valores informados."},{status:400});console.error("Operação financeira falhou",e instanceof Error?e.message:"Erro");return Response.json({error:"Não foi possível concluir. Tente novamente."},{status:500});}
const columns={trip:["tripDate","origin","destination","clientName","cargoType","freight","lossAlertPercent","freightPerTon","driverPercent","km","diesel","toll","oil","extras","extraItems","axles","loadedWeight","deliveredWeight","status","notes"],expense:["expenseDate","category","description","amount"],revenue:["revenueDate","category","description","amount"]} as const;
export const tables={trip:"trips",expense:"expenses",revenue:"revenues"} as const;
export type Kind=keyof typeof tables;
const snake=(s:string)=>s.replace(/[A-Z]/g,c=>"_"+c.toLowerCase());
export function writeRecord(kind:Kind,input:unknown,user:string,id:string,update=false){let value:Record<string,unknown>;if(kind==="trip"){const t=tripSchema.parse(input);if(t.freightPerTon!==null&&!(t.loadedWeight!=null&&t.loadedWeight>0))throw new Response("Informe o peso carregado.",{status:400});value={...t,freight:t.freightPerTon===null?t.freight:grossFreight(t.freightPerTon,t.loadedWeight!/1000),extras:Math.round(t.extraItems.reduce((n,e)=>n+e.amount,0)*100)/100,extraItems:JSON.stringify(t.extraItems)};}else value=(kind==="expense"?expenseSchema:revenueSchema).parse(input);const keys=columns[kind],values=keys.map(k=>value[k] as string|number|null);if(update)return db().prepare(`UPDATE ${tables[kind]} SET ${keys.map(k=>snake(k)+"=?").join(",")} WHERE id=? AND owner_id=?`).bind(...values,id,user);return db().prepare(`INSERT INTO ${tables[kind]} (id,owner_id,${keys.map(snake).join(",")}) VALUES (${Array(keys.length+2).fill("?").join(",")})`).bind(id,user,...values);}
function decode(row:Record<string,unknown>){return Object.fromEntries(Object.entries(row).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]));}
export async function records(user:string){const rows=await db().batch<Record<string,unknown>>([db().prepare("SELECT * FROM trips WHERE owner_id=? ORDER BY trip_date DESC,created_at DESC").bind(user),db().prepare("SELECT * FROM expenses WHERE owner_id=? ORDER BY expense_date DESC,created_at DESC").bind(user),db().prepare("SELECT * FROM revenues WHERE owner_id=? ORDER BY revenue_date DESC,created_at DESC").bind(user),db().prepare("SELECT name,cnpj,logo_key FROM companies WHERE owner_id=?").bind(user)]);return {trips:rows[0].results.map(r=>{const t=decode(r),items=JSON.parse(String(t.extraItems??"[]"));return {...t,extraItems:items.length?items:Number(t.extras)>0?[{category:"Outros",amount:Number(t.extras)}]:[]};}) as Trip[],expenses:rows[1].results.map(decode) as Expense[],revenues:rows[2].results.map(decode) as Revenue[],company:(rows[3].results[0]?decode(rows[3].results[0]):{name:"Rota Financeira",cnpj:"",logoKey:null}) as Company};}
